### ISSUE TITLE
Add request automation to data table.

### ISSUE THREAD

**Issue by KochTobi** [DKFZ-ODCF/GHGA-online#11]
## Add request automation to data table

It would be useful to somehow retrieve all information available and fill it out for the user.

How can be best enable the user to select one (or multiple) DAC from the table and trigger an autofill to the request form below?

- [x] Fill email template on form submission
- [x] Load values from the table into the form

**Comment by vinjana** [comment]
Consider letting the user select datasets with (checkboxes or so). Upon check, add datasets and corresponding DACs to table data-structure in JS. 

Maybe life-update of DOM in application form (below) using a condensed representation (DAC + list of corresponding datasets). 

Removal of datasets in form may also be a useful feature (in case something went wrong in the HTML table, scrolling up and finding the checkbox there is awkward).

But how to add the data from the JS data-structure to the form-data?

P.S: Normal HTML checkboxes look awkward and don't match the other design. How do they look like with this slate-theme? Can they be fit easily into the table?

**Comment by KochTobi** [comment]
I used bootstrap for the form. So maybe this can also be used for the table?

**Comment by vinjana** [comment]
Not sure but my original issue was not focused enough. I suggest we close this and make a new issue in case we are not happy with the checkboxes (e.g. to small). There is also already an issue for the deselection of data from the selection table.

**Comment by KochTobi** [comment]
Agreed.
