### ISSUE TITLE
Make text selectible in the data table

### ISSUE THREAD

**Issue by vinjana** [DKFZ-ODCF/GHGA-online#20]
Currently, it seems that neither in Firefox nor Vivaldi text can be selected in the table. This may be a nuissance for working with the table.

Make text selectible.

**Comment by KochTobi** [comment]
I think this is solved now. Originated probably from a CSS issue with the selection color being chosen incorrectly.

**Comment by vinjana** [comment]
Compare https://github.com/DKFZ-ODCF/GHGA-online/tree/fix-mark-highlighting

**Comment by KochTobi** [comment]
Oh I wasn't aware of that and pushed a hotfix removing custom selection styling to the master branch.
